version: '3.8'

services:
  app:
    build: .
    container_name: coworking-space-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coworking
      SPRING_DATASOURCE_USERNAME: coworking
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    container_name: coworking-db
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: coworking
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: